export const recipesRaw = [
    {
        idMeal: '53044',
        strMeal: 'Portuguese barbecued pork (Febras assadas)',
        strDrinkAlternate: '',
        strCategory: 'Pork',
        strArea: 'Portuguese',
        strInstructions: 'STEP 1rnrnCut the tenderloins into 5 equal-size pieces leaving the tail ends a little longer. Take a clear plastic bag and slip one of the pieces in. Bash it into an escalope the size of a side-plate with a rolling pin and repeat with the remaining pieces.rnrnSTEP 2rnrnPut the wine,paprika,some salt and pepper and the juice of u00bd a lemon in a bowl and add the pork.Leave to marinate for 20 - 30 minutes,while you get your barbecue to the stage where the coals are glowing but there are no flames.rnrnSTEP 3rnrnmake the chips,fill a basin with cool water and cut the potatoes into 3cm - thick chips.Soak them in the water for 5 minutes and thchange the water.Leave for 5 more minutes.Drain and then pat dry on a towel or with kitchen paper.rnrnST4rnrnHeat the oil in a deep fryer or a deep heavy- based pan with a lid to 130C and lower the chips into the oil(batches).Blanch for 8 - 10 minutes.Remove from the oil and drain well.Place on a tray to cool.Reheat the oil to 1(make sure itu2019s hot or your chips will be soggy) and lower the basket of chips into the oil(again,do this in batches). Leave to cook for 2 minutes and then give them a little shake.Cook for another minute or so untthey are well coloured and crisp to the touch.Drain well for a few minutes, tip into a bowl and sprinkle with sea salt.rnrnSTEP 5rnrnThe pork will cook quickly so do it in 2 batches.Take the pieces out of the marinade, rub them with oil, plate.Repeat with the remaining batch.rnrnSTEP 6rnrnServe by piling a plate with chips, a spoon of mayonnaise and a wedge of lemon.',
        strMealThumb: 'https://www.themealdb.com/images/media/meals/cybyue1614349443.jpg',
        strTags: '',
        strYoutube: 'https://www.youtube.com/watch?v=tVpsZaejyYU',
        strIngredient1: 'Pork',
        strIngredient2: 'White Wine',
        strIngredient3: 'Paprika',
        strIngredient4: '',
        strIngredient5: '',
        strIngredient6: '',
        strIngredient7: '',
        strIngredient8: '',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '2',
        strMeasure2: '200ml',
        strMeasure3: '1/2 tsp',
        strMeasure4: '2',
        strMeasure5: '',
        strMeasure6: '',
        strMeasure7: '',
        strMeasure8: '',
        strMeasure9: '',
        strMeasure10: ' ',
        strMeasure11: ' ',
        strMeasure12: ' ',
        strMeasure13: ' ',
        strMeasure14: ' ',
        strMeasure15: ' ',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource: 'https://www.olivemagazine.com/recipes/meat-and-poultry/febras-assadas-portuguese-barbecued-pork-served-with-lemon-and-mayo-on-chips/',
        strImageSource: '',
        strCreativeCommonsConfirmed: '',
        dateModified: ''
    },
    {
        idMeal: '53043',
        strMeal: 'Fish fofos',
        strDrinkAlternate: '',
        strCategory: 'Seafood',
        strArea: 'Portuguese',
        strInstructions: 'STEP 1rnrnPut the fish into a lidded pan and pour over enough water to cover. Bring to a simmer and gently poach for 10 minutes over a low heat with the lid on. Drain and flake the fish.rnrnSTEP 2rnrnPut the fish, potato, green chilli, coriander, cumin, black pepper, garlic and ginger in a large bowl.Season, add the rice flour, mix well and break in 1 egg.Stir the mixture and divide into 15, then form into small logs.Break the remaining eggs into a bowl and whisk lightly.Put the breadcrumbs into another bo Dip each fofo in the beaten egg followed by the breadcrumb mixture.Chill for 20 minutes.rnrnSTEP 3rnrnHeat 1 of oil in a large frying pan over a medium heat.Fry the fofos in batches for 2 minutes on each side, turning gently to get an even golden brown colour all over.Drain on kitchen paper and repeat with the remaining fof rnrnSTEP 4rnrnFor the onion salad, mix together the onion, coriander and lemon juice with a pinch of salt.Serve with the fofos and mango chutney.',
        strMealThumb: 'https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg',
        strTags: '',
        strYoutube: 'https://www.youtube.com/watch?v=YXUZHK2PrV8',
        strIngredient1: 'Haddock',
        strIngredient2: 'Potatoes',
        strIngredient3: 'Green Chilli',
        strIngredient4: '',
        strIngredient5: '',
        strIngredient6: '',
        strIngredient7: '',
        strIngredient8: '',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '600g',
        strMeasure2: '300g',
        strMeasure3: '1 chopped',
        strMeasure4: '',
        strMeasure5: '',
        strMeasure6: '',
        strMeasure7: '',
        strMeasure8: '',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource: 'https://www.olivemagazine.com/recipes/fish-and-seafood/fish-fofos/',
        strImageSource: '',
        strCreativeCommonsConfirmed: '',
        dateModified: ''
    },
    {
        idMeal: '53042',
        strMeal: 'Portuguese prego with green piri-piri',
        strDrinkAlternate: '',
        strCategory: 'Beef',
        strArea: 'Portuguese',
        strInstructions: 'STEP 1rnrnRub the garlic over the steaks then put in a sandwich bag and tip in the olive oil, sherry vinegar and parsley stalks.Smoosh everything together, then use a rolling pin to bash the steaks a few times.Leave for 1 - 2 hours.rnrnSTEP 2rnrnTo make the sauce, minutes on each side then rest on a plate.Put the ciabatta halves onto the plate, toasted - side down, to soak up any juices.rnrnSTEP 4rnrnSlice the steaks then stuff into the rolls with the green sauce and rocket.',
        strMealThumb: 'https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg',
        strTags: '',
        strYoutube: 'https://www.youtube.com/watch?v=FbIKfcDEPLA',
        strIngredient1: 'Garlic',
        strIngredient2: '',
        strIngredient3: '',
        strIngredient4: '',
        strIngredient5: '',
        strIngredient6: '',
        strIngredient7: '',
        strIngredient8: '',
        strIngredient9: '',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: '',
        strIngredient17: '',
        strIngredient18: '',
        strIngredient19: '',
        strIngredient20: '',
        strMeasure1: '1 clove',
        strMeasure2: '',
        strMeasure3: '',
        strMeasure4: '',
        strMeasure5: '',
        strMeasure6: '',
        strMeasure7: '',
        strMeasure8: '',
        strMeasure9: '',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: ' ',
        strMeasure16: ' ',
        strMeasure17: ' ',
        strMeasure18: ' ',
        strMeasure19: ' ',
        strMeasure20: ' ',
        strSource: 'https://www.olivemagazine.com/recipes/meat-and-poultry/portuguese-prego-with-green-piri-piri/',
        strImageSource: '',
        strCreativeCommonsConfirmed: '',
        dateModified: ''
    }
];

export const ingredients = [
    { strIngredient: 'Salt', strDescription: 'Sodium chloride', idIngredient: '1' },
    { strIngredient: 'Sugar', strDescription: 'Sucrose', idIngredient: '2' },
    { strIngredient: 'Basil', strDescription: 'Sweet basil', idIngredient: '3' },
    { strIngredient: 'Butter', strDescription: 'Dairy product', idIngredient: '4' },
    { strIngredient: 'Pepper', strDescription: 'Black pepper', idIngredient: '5' },
    { strIngredient: 'Paprika', strDescription: 'Ground spice', idIngredient: '6' },
];
